### ISSUE TITLE
Hunter hdf5 package builds, but does not link, the C++ library.

### ISSUE THREAD

**Issue by mwbuksas** [hunter-packages/hdf5#1]
E.g. A sample link line:

`/usr/bin/c++  -g  -rdynamic CMakeFiles/test.dir/test.o  -o test libMyLib.a /home/bar/.hunter/_Base/d238dc1/de21555/1bd60b8/Install/lib/libhdf5_debugd.a -lm -ldl /home/bar/.hunter/_Base/d238dc1/de21555/1bd60b8/Install/lib/libzd.a /home/bar/.hunter/_Base/d238dc1/de21555/1bd60b8/Install/lib/libszipd.a -lstdc++fs`

The library `libhdf5_hl_cpp_debugd.a` is present in the same directory as `libhdf5_debugd.a` but doesn't appear on the link line. This is a debug build. 

Configuration:

    hunter_add_package(hdf5)
    find_package(ZLIB CONFIG REQUIRED)
    find_package(szip CONFIG REQUIRED)
    find_package(hdf5 CONFIG REQUIRED)

    target_link_libraries( MyLib Boost::boost Eigen3::Eigen hdf5 stdc++fs)

**Comment by fer-marino** [comment]
I'm having the same problem. Is there a fix or a workaround?

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
